services:
  postgres:
    image: postgres:latest
    container_name: prisma-redlock-test-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma_redlock_test_db
    ports:
      - "5432:5432"
    volumes:
      - prisma_redlock_test_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: prisma-redlock-test-redis
    ports:
      - "6379:6379"
    volumes:
      - prisma_redlock_test_redis_data:/data

volumes:
  prisma_redlock_test_postgres_data:
  prisma_redlock_test_redis_data:
